name: upload-codecov-report
run-name: upload-codecov-report
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
